
export const musicGenres = [
    "pop",
    "alternative rock",
    "indie rock",
    "pop rock",
    "electronic",
    "folk",
    "country",
    "rap",
    "soul",
    "jazz",
    "metal",
    "trap",
    "heavy metal",
    "blues",
    "hard rock",
    "punk",
    "indie pop",
    "progressive rock",
    "synthpop",
    "hip-hop",
    "reggae",
    "electropop",
    "funk",
    "psychedelic rock",
    "punk rock",
    "indie",
    "classic rock",
    "new wave",
    "classical",
    "dance",
    "metalcore",
    "post-hardcore",
    "progressive metal",
    "emo",
    "pop punk",
    "alternative",
    "post-punk",
    "experimental",
    "soundtrack",
    "gospel",
    "ambient",
    "swing",
    "rnb",
    "thrash metal",
    "drum and bass",
    "death metal",
    "cloud rap",
    "house",
    "trance",
    "disco",
    "lo-fi",
    "dream pop",
    "shoegaze",
    "industrial",
    "nu metal",
    "dub",
    "grunge",
    "power metal",
    "christian",
    "emo rap",
    "garage rock",
    "melodic death metal",
    "dancehall",
    "k-pop",
    "hardcore",
    "black metal",
    "comedy",
    "latin",
    "deathcore",
    "acoustic",
    "doom metal",
    "screamo",
    "techno",
    "j-pop",
    "electro",
    "grime",
    "dubstep",
    "britpop",
    "math rock",
    "trip-hop",
    "chillwave",
    "alt-country",
    "worship",
    "psychedelic",
    "chillout",
    "reggaeton"
]
